### ISSUE TITLE
/roll uses non-existent emoji and is indecipherable

### ISSUE THREAD

**Issue by scottmk** [c-bec-k/fateBot#3]
The `/roll` command seems to use emoji that don't get installed to the server. `:dF1:` and `:dF0:`

What's more, the emoji codes are indecipherable, because I got two results that simply don't jive:

```
You got a Fair(+2) result!
:dF1: :dF0: :dF1: :dF0: +0
```
and

```
You got a Terrible(-2) result!
:dF1: :dF1: :dF0: :dF0: +0
```

See screenshot below:
<img width="317" alt="Screen Shot 2022-01-21 at 01 09 29" src="https://user-images.githubusercontent.com/3020184/150499295-02959d93-a76d-444b-b213-04821dfc4a74.png">.

**Comment by c-bec-k** [comment]
I'm order to see the emojis you either need to upload them too your server or give the `@everyone` permission to use external emojis.

I thought I had the emojis in the repo, but I guess not. I'll try to get them added ASAP.

**Comment by scottmk** [comment]
That makes sense, but it still doesn't explain the results. Shouldn't there be 3 emojis?

**Comment by scottmk** [comment]
Just to be more clear: both results show two `:dF1:` emoji, and two `:dF0:` emoji, but one is a -2 result, and one is a +2 result, which indicates to me that the `-` and `+` rolls are somehow both mapped to `:dF1`. Shouldn't these have separate aliases?

**Comment by c-bec-k** [comment]
That's an artifact of the upload process to Discord that I haven't yet fixed.

I originally had `df-1` and `df+1` as the file names for the `–` and `+` sides. But when I uploaded to Discord it stripped out the `–` and the `+` and left it as `df1`.

I'll get the emojis updated soon, I hope, so it's `dfm` for minus and `dfp` for plus (unless you have a better idea for names that don't include symbols?).

**Comment by scottmk** [comment]
Thanks for the response! I think `:dfm:` and `:dfp:` are perfectly sensible.

**Comment by scottmk** [comment]
I created a PR with the changes you proposed: https://github.com/c-bec-k/fateBot/pull/4

**Comment by scottmk** [comment]
Also it turns out it still works as long as you enable external server emoji. I'm guessing since it uses the Snowflake IDs, the name collisions don't matter. I assume you'd have to change the name aliases on your server since we're using your Snowflake IDs?

**Comment by c-bec-k** [comment]
> Also it turns out it still works as long as you enable external server emoji. I'm guessing since it uses the Snowflake IDs, the name collisions don't matter. I assume you'd have to change the name aliases on your server since we're using your Snowflake IDs?

Yeah, it's using the emoji ID so even though the names of the dice don't make that much sense without the permission at least the emojis are displaying properly.

In any case, I was able to merge your pull req and get the app updated. Thanks for the assist!
